### ISSUE TITLE
Build failing on Mac OS 10.12.2 Sierra

### ISSUE THREAD

**Issue by Snawoot** [Tox/homebrew-tox#32]
Console output:
```
MacBook-Pro-lka:qTox lka$ brew install --HEAD qtox
==> Installing qtox from tox/tox
==> Installing dependencies for tox/tox/qtox: x264, ffmpeg, openal-soft, Tox/tox/libfilteraudio
==> Installing tox/tox/qtox dependency: x264
==> Downloading https://homebrew.bintray.com/bottles/x264-r2728.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring x264-r2728.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/x264/r2728: 11 files, 3.3M
==> Installing tox/tox/qtox dependency: ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-3.2.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ffmpeg-3.2.2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/3.2.2: 239 files, 50.4M
==> Installing tox/tox/qtox dependency: openal-soft
==> Downloading https://homebrew.bintray.com/bottles/openal-soft-1.17.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openal-soft-1.17.2.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS provides OpenAL.framework.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openal-soft/lib
    CPPFLAGS: -I/usr/local/opt/openal-soft/include
    PKG_CONFIG_PATH: /usr/local/opt/openal-soft/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openal-soft/1.17.2: 21 files, 760.1K
==> Installing tox/tox/qtox dependency: Tox/tox/libfilteraudio
==> Cloning https://github.com/irungentoo/filter_audio.git
Cloning into '/Users/lka/Library/Caches/Homebrew/libfilteraudio--git'...
remote: Counting objects: 108, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 108 (delta 3), reused 93 (delta 3), pack-reused 0
Receiving objects: 100% (108/108), 241.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3/3), done.
==> Checking out branch master
==> make install PREFIX=/usr/local/Cellar/libfilteraudio/audio
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/filter_audio.h
Target /usr/local/include/filter_audio.h
already exists. You may want to remove it:
  rm '/usr/local/include/filter_audio.h'

To force the link and overwrite all conflicting files:
  brew link --overwrite libfilteraudio

To list all files that would be deleted:
  brew link --overwrite --dry-run libfilteraudio

Possible conflicting files are:
/usr/local/include/filter_audio.h
/usr/local/lib/libfilteraudio.0.0.0.dylib
/usr/local/lib/libfilteraudio.0.dylib -> /usr/local/lib/libfilteraudio.0.0.0.dylib
/usr/local/lib/libfilteraudio.a
/usr/local/lib/libfilteraudio.dylib -> /usr/local/lib/libfilteraudio.0.dylib
/usr/local/lib/pkgconfig/filteraudio.pc
==> Summary
🍺  /usr/local/Cellar/libfilteraudio/audio: 9 files, 407.7K, built in 7 seconds
==> Installing tox/tox/qtox --HEAD
==> Cloning git://github.com/tux3/qTox
Cloning into '/Users/lka/Library/Caches/Homebrew/qtox--git'...
remote: Counting objects: 3398, done.
remote: Compressing objects: 100% (2871/2871), done.
remote: Total 3398 (delta 641), reused 2974 (delta 496), pack-reused 0
Receiving objects: 100% (3398/3398), 4.34 MiB | 1.54 MiB/s, done.
Resolving deltas: 100% (641/641), done.
==> Checking out branch master
==> qmake
==> make
Last 15 lines from /Users/lka/Library/Logs/Homebrew/qtox/02.make:
                                                           ^
src/core/core.h:221:39: error: unknown type name 'TOX_CONFERENCE_STATE_CHANGE'
                                      TOX_CONFERENCE_STATE_CHANGE change, void* core);
                                      ^
src/core/core.h:228:30: error: unknown type name 'TOX_ERR_CONFERENCE_PEER_QUERY'
    bool parsePeerQueryError(TOX_ERR_CONFERENCE_PEER_QUERY error) const;
                             ^
src/core/core.h:229:35: error: unknown type name 'TOX_ERR_CONFERENCE_JOIN'
    bool parseConferenceJoinError(TOX_ERR_CONFERENCE_JOIN error) const;
                                  ^
src/core/core.h:105:36: error: use of undeclared identifier 'TOX_CONFERENCE_TYPE_AV'
    int createGroup(uint8_t type = TOX_CONFERENCE_TYPE_AV);
                                   ^
8 errors generated.
make: *** [group.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tox/homebrew-tox/issues
```

`libtoxcore` is already installed on this system.

**Comment by gfairchild** [comment]
I'm seeing the same thing on 10.11.6.

**Comment by twang2218** [comment]
Same here. Also, 10.12.2

```bash
$ brew install --HEAD libtoxcore toxic                                      [f776dde]
==> Installing libtoxcore from tox/tox
==> Installing dependencies for tox/tox/libtoxcore: libsodium, check, opus, libvpx
==> Installing tox/tox/libtoxcore dependency: libsodium
==> Downloading https://homebrew.bintray.com/bottles/libsodium-1.0.11.sierra.bottle.tar
######################################################################## 100.0%
==> Pouring libsodium-1.0.11.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libsodium/1.0.11: 66 files, 1.1M
==> Installing tox/tox/libtoxcore dependency: check
==> Downloading https://homebrew.bintray.com/bottles/check-0.10.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring check-0.10.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/check/0.10.0: 43 files, 843.0K
==> Installing tox/tox/libtoxcore dependency: opus
==> Downloading https://homebrew.bintray.com/bottles/opus-1.1.3.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring opus-1.1.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/opus/1.1.3: 15 files, 857.3K
==> Installing tox/tox/libtoxcore dependency: libvpx
==> Downloading https://homebrew.bintray.com/bottles/libvpx-1.6.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libvpx-1.6.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libvpx/1.6.0: 16 files, 1.4M
==> Installing tox/tox/libtoxcore --HEAD
==> Cloning git://github.com/irungentoo/toxcore
Cloning into '/Users/taowang/Library/Caches/Homebrew/libtoxcore--git'...
remote: Counting objects: 207, done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 207 (delta 10), reused 58 (delta 0), pack-reused 0
Receiving objects: 100% (207/207), 476.19 KiB | 286.00 KiB/s, done.
Resolving deltas: 100% (10/10), done.
==> Checking out branch master
==> autoreconf -if
==> ./configure --prefix=/usr/local/Cellar/libtoxcore/HEAD-dcf2aaa --disable-testing
==> make
==> make install
==> Caveats
libtoxcore has no UI. If you want to make use of it, try Toxic for a CLI:
  brew install --HEAD toxic
or uTox for a GUI (X11):
  brew install --HEAD utox
==> Summary
🍺  /usr/local/Cellar/libtoxcore/HEAD-dcf2aaa: 24 files, 1.1M, built in 57 seconds
==> Installing toxic from tox/tox
==> Tapping homebrew/dupes
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 39, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 39 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (39/39), done.
Tapped 35 formulae (98 files, 116.8K)
==> Installing dependencies for tox/tox/toxic: homebrew/dupes/ncurses, freealut, libconfig, qrencode
==> Installing tox/tox/toxic dependency: homebrew/dupes/ncurses
==> Using the sandbox
==> Downloading https://ftpmirror.gnu.org/ncurses/ncurses-6.0.tar.gz
==> Downloading from http://gnu.uberglobalmirror.com/ncurses/ncurses-6.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ncurses/6.0_2 --enable-pc-files --with-pkg-c
==> make
==> make install
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/ncurses/lib
    CPPFLAGS: -I/usr/local/opt/ncurses/include
    PKG_CONFIG_PATH: /usr/local/opt/ncurses/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/ncurses/6.0_2: 3,828 files, 10.4M, built in 3 minutes 43 seconds
==> Installing tox/tox/toxic dependency: freealut
==> Downloading https://homebrew.bintray.com/bottles/freealut-1.1.0.sierra.bottle.tar.g
######################################################################## 100.0%
==> Pouring freealut-1.1.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/freealut/1.1.0: 12 files, 140.5K
==> Installing tox/tox/toxic dependency: libconfig
==> Downloading https://homebrew.bintray.com/bottles/libconfig-1.6.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libconfig-1.6.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libconfig/1.6: 21 files, 517.7K
==> Installing tox/tox/toxic dependency: qrencode
==> Downloading https://homebrew.bintray.com/bottles/qrencode-3.4.4.sierra.bottle.tar.g
######################################################################## 100.0%
==> Pouring qrencode-3.4.4.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/qrencode/3.4.4: 12 files, 174.5K
==> Installing tox/tox/toxic --HEAD
==> Cloning git://github.com/Tox/toxic
Cloning into '/Users/taowang/Library/Caches/Homebrew/toxic--git'...
remote: Counting objects: 118, done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 118 (delta 21), reused 24 (delta 0), pack-reused 0
Receiving objects: 100% (118/118), 1.11 MiB | 168.00 KiB/s, done.
Resolving deltas: 100% (21/21), done.
==> Checking out branch master
==> make PREFIX='/usr/local/Cellar/toxic/HEAD-7a7402f' DISABLE_DESKTOP_NOTIFY=YES DISAB
Last 15 lines from /Users/taowang/Library/Logs/Homebrew/toxic/01.make:
                                                                                ^
2 errors generated.
make: *** [/private/tmp/toxic-20170110-91471-1xv0i6i/build/autocomplete.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /private/tmp/toxic-20170110-91471-1xv0i6i/src/avatars.c:27:
In file included from /private/tmp/toxic-20170110-91471-1xv0i6i/src/misc_tools.h:27:
In file included from /private/tmp/toxic-20170110-91471-1xv0i6i/src/windows.h:37:
/private/tmp/toxic-20170110-91471-1xv0i6i/src/toxic.h:119:52: error: unknown type name 'TOX_CONFERENCE_TYPE'
void on_groupinvite(Tox *m, uint32_t friendnumber, TOX_CONFERENCE_TYPE type, const uint8_t *group_pub_key,
                                                   ^
/private/tmp/toxic-20170110-91471-1xv0i6i/src/toxic.h:121:81: error: unknown type name 'TOX_CONFERENCE_STATE_CHANGE'
void on_group_namelistchange(Tox *m, uint32_t groupnumber, uint32_t peernumber, TOX_CONFERENCE_STATE_CHANGE change,
                                                                                ^
2 errors generated.
make: *** [/private/tmp/toxic-20170110-91471-1xv0i6i/build/avatars.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tox/homebrew-tox/issues
```

**Comment by blacRose** [comment]
Ah. I get the `TOX_CONFERENCE_TYPE` on 10.12.3 Beta, as well.

**Comment by JFreegman** [comment]
>Cloning git://github.com/irungentoo/toxcore

This is the problem. It should be toktok/c-toxcore. I don't use OSX nor know anything about homebrew, so it might be better to heed the advice:

>If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tox/homebrew-tox/issues

**Comment by twang2218** [comment]
At https://github.com/Tox/homebrew-tox/blob/master/Formula/toxic.rb#L7:

```ruby
  depends_on "libtoxcore"
```

And at https://github.com/Tox/homebrew-tox/blob/master/Formula/libtoxcore.rb#L4:

```ruby
  head "git://github.com/irungentoo/toxcore", :using => :git
```

I think that's the reason why it's cloning `git://github.com/irungentoo/toxcore`.

@JFreegman should I submit a PR for update that link?

**Comment by twang2218** [comment]
Created a PR #34 for this issue.

**Comment by Mattel88** [comment]
How do I run the formula?

**Comment by blacRose** [comment]
`brew tap Tox/homebrew-tox`
`brew install <some formula`

**Comment by stal888** [comment]
closing this because #37 should have fixed it. please re-open this if it has not :)

**Comment by Snawoot** [comment]
Still no luck, but I have only 5 errors now:
```
MacBook-Pro-lka:~ lka$ brew install --HEAD qtox
==> Installing qtox from tox/tox
==> Installing dependencies for tox/tox/qtox: libsodium, check, pkg-config, opus, libvpx, qt5, x264, ffmpeg, libpng, openssl, sqlcipher
==> Installing tox/tox/qtox dependency: libsodium
==> Downloading https://homebrew.bintray.com/bottles/libsodium-1.0.12.sierra.bot
######################################################################## 100.0%
==> Pouring libsodium-1.0.12.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libsodium/1.0.12: 68 files, 1.2MB
==> Installing tox/tox/qtox dependency: check
==> Downloading https://homebrew.bintray.com/bottles/check-0.11.0.sierra.bottle.
######################################################################## 100.0%
==> Pouring check-0.11.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/check/0.11.0: 42 files, 517.2KB
==> Installing tox/tox/qtox dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.sierra.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.29.2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2: 11 files, 627KB
==> Installing tox/tox/qtox dependency: opus
==> Downloading https://homebrew.bintray.com/bottles/opus-1.1.4.sierra.bottle.ta
######################################################################## 100.0%
==> Pouring opus-1.1.4.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/opus/1.1.4: 16 files, 858.4KB
==> Installing tox/tox/qtox dependency: libvpx
==> Downloading https://homebrew.bintray.com/bottles/libvpx-1.6.1.sierra.bottle.
######################################################################## 100.0%
==> Pouring libvpx-1.6.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libvpx/1.6.1: 17 files, 1.4MB
==> Installing tox/tox/qtox dependency: qt5
==> Downloading https://homebrew.bintray.com/bottles/qt-5.8.0_2.sierra.bottle.ta
######################################################################## 100.0%
==> Pouring qt-5.8.0_2.sierra.bottle.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local.

Qt 5 has CMake issues when linked

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qt/lib
    CPPFLAGS: -I/usr/local/opt/qt/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/qt/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/qt/5.8.0_2: 8,667 files, 246.2MB
==> Installing tox/tox/qtox dependency: x264
==> Downloading https://homebrew.bintray.com/bottles/x264-r2748.sierra.bottle.ta
######################################################################## 100.0%
==> Pouring x264-r2748.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/x264/r2748: 11 files, 3.3MB
==> Installing tox/tox/qtox dependency: ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-3.3.sierra.bottle.ta
######################################################################## 100.0%
==> Pouring ffmpeg-3.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/3.3: 243 files, 50.7MB
==> Installing tox/tox/qtox dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.29.sierra.bottle
######################################################################## 100.0%
==> Pouring libpng-1.6.29.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.29: 26 files, 1.2MB
==> Installing tox/tox/qtox dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2k.sierra.bottl
######################################################################## 100.0%
==> Pouring openssl-1.0.2k.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2k: 1,696 files, 12MB
==> Installing tox/tox/qtox dependency: sqlcipher
==> Downloading https://homebrew.bintray.com/bottles/sqlcipher-3.4.1.sierra.bott
######################################################################## 100.0%
==> Pouring sqlcipher-3.4.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/sqlcipher/3.4.1: 12 files, 2.0MB
==> Installing tox/tox/qtox --HEAD
==> Cloning git://github.com/qTox/qTox
Updating /Users/lka/Library/Caches/Homebrew/qtox--git
==> Checking out branch master
==> qmake
==> make
Last 15 lines from /Users/lka/Library/Logs/Homebrew/qtox/02.make:
    bool parsePeerQueryError(TOX_ERR_CONFERENCE_PEER_QUERY error) const;
                             ^
./src/core/core.h:207:35: error: unknown type name 'TOX_ERR_CONFERENCE_JOIN'
    bool parseConferenceJoinError(TOX_ERR_CONFERENCE_JOIN error) const;
                                  ^
./src/core/core.h:90:36: error: use of undeclared identifier 'TOX_CONFERENCE_TYPE_AV'
    int createGroup(uint8_t type = TOX_CONFERENCE_TYPE_AV);
                                   ^
src/audio/audio.cpp:495:20: warning: comparison of integers of different signs: 'ALint' (aka 'int') and 'const unsigned int' [-Wsign-compare]
        if (queued >= BUFFER_COUNT) {
            ~~~~~~ ^  ~~~~~~~~~~~~
compiling src/chatlog/chatlinecontentproxy.cpp
1 warning and 5 errors generated.
make: *** [audio.o] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/Tox/homebrew-tox/issues

MacBook-Pro-lka:~ lka$ 
```

**Comment by Snawoot** [comment]
@stal888 Requesting issue reopen.

**Comment by publicarray** [comment]
Looking at your logs from the previous run there was an issue with linking libfilteraudio.
`brew link --overwrite libfilteraudio` should fix it. Then run `brew install --HEAD qtox` again. 
If that does not work you run `brew doctor` and try to fix any warnings that might appear.

**Comment by Snawoot** [comment]
Executed both commands, now brew doctor output is clean, but problem persists:
```
MacBook-Pro-lka:~ lka$ brew doctor
Your system is ready to brew.
MacBook-Pro-lka:~ lka$ brew install --HEAD qtox
==> Installing qtox from tox/tox
==> Cloning git://github.com/qTox/qTox
Updating /Users/lka/Library/Caches/Homebrew/qtox--git
fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)
Error: Failed to download resource "qtox"
Failure while executing: git fetch -q origin
MacBook-Pro-lka:~ lka$ brew install --HEAD qtox
==> Installing qtox from tox/tox
==> Cloning git://github.com/qTox/qTox
Updating /Users/lka/Library/Caches/Homebrew/qtox--git
==> Checking out branch master
==> qmake
==> make
Last 15 lines from /Users/lka/Library/Logs/Homebrew/qtox/02.make:
    bool parsePeerQueryError(TOX_ERR_CONFERENCE_PEER_QUERY error) const;
                             ^
./src/core/core.h:207:35: error: unknown type name 'TOX_ERR_CONFERENCE_JOIN'
    bool parseConferenceJoinError(TOX_ERR_CONFERENCE_JOIN error) const;
                                  ^
./src/core/core.h:90:36: error: use of undeclared identifier 'TOX_CONFERENCE_TYPE_AV'
    int createGroup(uint8_t type = TOX_CONFERENCE_TYPE_AV);
                                   ^
src/audio/audio.cpp:495:20: warning: comparison of integers of different signs: 'ALint' (aka 'int') and 'const unsigned int' [-Wsign-compare]
        if (queued >= BUFFER_COUNT) {
            ~~~~~~ ^  ~~~~~~~~~~~~
compiling src/chatlog/chatlinecontentproxy.cpp
1 warning and 5 errors generated.
make: *** [audio.o] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/Tox/homebrew-tox/issues

MacBook-Pro-lka:~ lka$ 
```
Also attaching full build logs in this gist: https://gist.github.com/Snawoot/a388f49fe8f1f19b3b6a8a2910231ff4

**Comment by publicarray** [comment]
Hm I've run the install on my machine and it ran fine (So the brew formula itself is working, so I think it is something specific to your machine). Besides a `brew reinstall --HEAD qtox` I'm out of options, sorry. Maybe the nice folks over at https://github.com/qTox/qTox can help you. 

/cc @stal888 Do you have any other ideas? 🤔

**Comment by Snawoot** [comment]
Unfortunately, `brew reinstall --HEAD qtox` didn't helped. Also there are other users experienced same problem. Can someone confirm formula works for him now?

@gfairchild
@twang2218 
@blacRose

**Comment by publicarray** [comment]
Is it possible you don't have the latest changes in this repo?  Try re-tapping the repo `brew untap tox && brew update && brew cleanup -s && brew tap tox/tox`

**Comment by publicarray** [comment]
Actually nevermind that.  You need to update the dependency becourse they are versioned by git. i.e need to be recompiled manually. So `brew reinstall --HEAD libtoxcore` should do it. Sorry it took so long. I'm fairly new to this.

**Comment by Snawoot** [comment]
Thank you, it works! Command `brew reinstall --HEAD libtoxcore` resolved issue.

**Comment by sysfu** [comment]
Confirmed that `brew reinstall --HEAD libtoxcore` command solved brew build issue for `utox` on my 10.12.4 MacOS Sierra system too.

**Comment by gfairchild** [comment]
I can also confirm that `brew reinstall --HEAD libtoxcore` built for me!
